"""add_wallet_operation_type

Revision ID: 97ad75f0f684
Revises: cdba3a405b9f
Create Date: 2025-12-29 07:28:27.110144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ad75f0f684'
down_revision: Union[str, Sequence[str], None] = 'cdba3a405b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    wallet_operation_enum = sa.Enum('DEPOSIT', 'WITHDRAW', name='walletoperationtype')
    wallet_operation_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE wallet_operations ALTER COLUMN type TYPE walletoperationtype USING type::walletoperationtype;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_operations', 'type',
               existing_type=sa.Enum('DEPOSIT', 'WITHDRAW', name='walletoperationtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum('DEPOSIT', 'WITHDRAW', name='walletoperationtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###