"""init

Revision ID: cdba3a405b9f
Revises: 
Create Date: 2025-12-27 10:43:03.349567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdba3a405b9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_operations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('walletId', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('externalOperationId', sa.String(), nullable=False),
    sa.Column('traceId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('externalOperationId')
    )
    op.create_index(op.f('ix_wallet_operations_id'), 'wallet_operations', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_operations_walletId'), 'wallet_operations', ['walletId'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_userId'), 'wallets', ['userId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_userId'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_wallet_operations_walletId'), table_name='wallet_operations')
    op.drop_index(op.f('ix_wallet_operations_id'), table_name='wallet_operations')
    op.drop_table('wallet_operations')
    # ### end Alembic commands ###