from enum import Enum

class Codes(str, Enum):
    LIVE_OK = "LIVE_OK"
    HEALTH_OK = "HEALTH_OK"
    READY_OK = "READY_OK"
    WALLET_CREATED = "WALLET_CREATED"
    WALLET_FETCHED_OK = "WALLET_FETCHED_OK"
    WALLET_DEPOSIT_OK = "WALLET_DEPOSIT_OK"
    WALLET_WITHDRAW_OK = "WALLET_WITHDRAW_OK"
    WALLET_DELETED = "WALLET_DELETED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    WALLET_NOT_FOUND = "WALLET_NOT_FOUND"
    WALLET_ALREADY_EXISTS = "WALLET_ALREADY_EXISTS"
    WALLET_INSUFFICIENT_FUNDS = "WALLET_INSUFFICIENT_FUNDS"
    WALLET_INTERNAL_ERROR = "WALLET_INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    WALLET_OPERATION_DUPLICATE = "WALLET_OPERATION_DUPLICATE"
    WALLET_NOT_EMPTY = "WALLET_NOT_EMPTY"
